CREATE TABLE IF NOT EXISTS game (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      createdAt TEXT NOT NULL,
      updatedAt TEXT NULL
      );

CREATE TABLE IF NOT EXISTS player (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      playerName TEXT NOT NULL,
      gameId INTEGER NOT NULL,
      FOREIGN KEY (gameId) REFERENCES game (id) ON DELETE CASCADE
      );

CREATE TABLE IF NOT EXISTS rounds (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      round INTEGER NOT NULL,
      gameId INTEGER NOT NULL,
      FOREIGN KEY (gameId) REFERENCES game (id) ON DELETE CASCADE
      );

CREATE TABLE IF NOT EXISTS score (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      score INTEGER NOT NULL,
      roundId INTEGER NOT NULL,
      FOREIGN KEY (roundId) REFERENCES rounds (id) ON DELETE CASCADE
      );


